### ISSUE TITLE
How to change SKActivityIndicator background color?

### ISSUE THREAD

**Issue by hemangshah** [SachK13/SKActivityIndicatorView#1]
Hi @SachK13, I couldn't find a way to change the same? Is there any?

**Comment by Vinith253** [comment]
Hey @SachK13, I would like to change the background color. Is there any option to do it?

**Comment by SachK13** [comment]
@hemangshah @VinithNivvin current version doesn't have functionality to change background colour but will sure add it to next version, thanks for using it.
