### ISSUE TITLE
Crash on ios 13

### ISSUE THREAD

**Issue by iosMaher** [SachK13/SKActivityIndicatorView#10]
Crash on ios 13, window!.frame

Fix :
in -> SKActivityIndicatorView.swift
Replace ↓
Old:
        let delegate: UIApplicationDelegate = UIApplication.shared.delegate!
        if let windowObj = delegate.window {
            window = windowObj
        } else {
            window = UIApplication.shared.keyWindow!
        }

New:
        if let delegate = UIApplication.shared.delegate as? AppDelegate {
            if let windowObj = delegate.window {
                window = windowObj
            } else {
                window = UIApplication.shared.keyWindow!
            }
        }

Don't forget to add ↓ in AppDelegate
var window: UIWindow?

**Comment by YasmeenHelles** [comment]
Use of undeclared type 'AppDelegate' :(
Problem not solved

**Comment by SachK13** [comment]
@iosMaher @YasmeenHelles This has been fixed in 1.0.0. and code has been updated to support iOS 13 and above with Swift 5.x+.
