### ISSUE TITLE
Not Compatible with Xcode 10.

### ISSUE THREAD

**Issue by abhishekthanvi8** [SachK13/SKActivityIndicatorView#5]

**Comment by Savchukv** [comment]
Hi! I do not have problems with Xcode 10.

**Comment by armintelker** [comment]
@abhishekthanvi8 
Hey here https://github.com/SachK13/SKActivityIndicatorView/pull/6 are fixes to support the newest swift 4.2 version. 
Maybe it will help.

**Comment by SachK13** [comment]
@abhishekthanvi8 Now supporting to Xcode 10 & Swift 4.2.
