### ISSUE TITLE
Did you updated cocoapods for Swift 4.2?

### ISSUE THREAD

**Issue by shahdhiren** [SachK13/SKActivityIndicatorView#7]
I tried updating to cocoapod, but looks pod version is still old.

I used `pod 'SKActivityIndicatorView'` without any specific version and I received SKActivityIndicatorView (0.1.0) version.

**Comment by gblock92** [comment]
Yes, I tried updating too and I'm also getting 0.1.0

**Comment by shahdhiren** [comment]
which version did you updated?

**Comment by Gruppio** [comment]
I think that @SachK13 did perform the update of the code but it forget to update the pod version in the .podspec file and push the pod to cocoapods repo :-)

**Comment by TaimoorSaeed** [comment]
Is there a way around that?

**Comment by solariserj** [comment]
@TaimoorSaeed  SachK13 something mix in last commit. 
You can use previous commit for swift 4.2  like 
pod 'SKActivityIndicatorView' , :git => 'https://github.com/SachK13/SKActivityIndicatorView.git', :commit => 'bb0a954'  

before @SachK13  fixed them

**Comment by SachK13** [comment]
@shahdhiren @gblock92 @Gruppio @TaimoorSaeed @solariserj updated the podspec file with version 1.0.0 & code has been updated to support iOS 13 & above with Swift 5.x+.
